-- Delegate booking support.
-- Adds booking_reference (human-facing short ticket reference, generated by
-- the app at booking creation) and confirmation_email_sent_at (null until the
-- transactional send succeeds). The partial index supports a future admin
-- view of "bookings with unsent confirmations older than N minutes".

alter table public.bookings
  add column booking_reference text unique,
  add column confirmation_email_sent_at timestamptz;

create index bookings_unsent_confirmation_idx
  on public.bookings (created_at)
  where confirmation_email_sent_at is null;

comment on column public.bookings.booking_reference is
  'Human-facing unique ticket reference, format I27-XXXXXXX using a reduced alphabet that excludes visually ambiguous characters. Generated at booking creation.';

comment on column public.bookings.confirmation_email_sent_at is
  'When the confirmation email was successfully dispatched by Resend. Null until sent.';
